# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARFitHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'IQKeyboardManager'
  # Pods for ARFitHelper

end
